
const ValidationRegPatterns = {
        regTextField1 :new RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regTextField2 :new RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regAmountField :new RegExp(/^(?<=^| )\d+(\.\d+)?(?=$| )*$/),
        regEntryField :new RegExp(/^(\d+(\.\d{0,2})?|\.?\d{1,2})$/),
        regTextArea1 :new RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regTextArea2 :new RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regPercentageField :new RegExp(/^100(\.0{0,2})? *?$|^\d{1,2}(\.\d{1,2})? *?$/),
        regPinCode :new RegExp(/^[0-9]{6}/),
        regMobile :new RegExp(/^([+]\d{2}[ ])?\d{10}$/),
        regIndianMobile :new RegExp(/^[0-9- ]+$/),
        regEmail :new RegExp(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9]+\.[A-Za-z]+$/),
        regName :new RegExp(/^[a-zA-Z ]+$/),
        regOtherReligion :new RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regBankAccountNumber :new RegExp(/^[0-9]*$/),
        regIfscNumber :new RegExp(/^[A-Za-z]{4}[a-zA-Z0-9]{7}$/),
        regPan:new RegExp(/^([a-zA-Z]){5}[0-9]{4}[a-zA-Z]{1}$/),
        regGstin:new RegExp(/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9]{1}Z[0-9]{1}$/),
        regExpChartAccountName:new RegExp(/^[0-9a-zA-Z- ]*$/),
        regExpdocument : RegExp(/^[a-zA-Z0-9()#.,-/ ]*$/),
        regUserId:new RegExp(/^[A-Za-z0-9_]*$/),
        regNumbersOnly:new RegExp(/^[0-9]*$/),
        regAlphaNumericOnly:new RegExp(/^[A-Za-z0-9]*$/),
        regPrefixName :new RegExp(/^[a-zA-Z]+$/),
        regPassword :new RegExp(/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[.,-/&@])[A-Za-z\d.,-/&@]{8,20}$/),
        regDepartment :new  RegExp(/^[ A-Za-z0-9\s&/.-]*$/),
        regShortDepartment : new RegExp(/^[a-zA-Z]+$/),
        regDescription : new RegExp(/^[a-zA-Z0-9-.,/# ]*$/),
        regProgramCode : new RegExp(/^[ A-Za-z0-9()_@./#+-]*$/),
        regProgramName : new RegExp(/^[ A-Za-z0-9()_@./#+-]*$/),
        regtermName : new RegExp(/^[ A-Za-z0-9().,:-]*$/),
        regCourseOrDesignationName : new RegExp(/^[ A-Za-z0-9#,-/.()]*$/),
        regCourseCode : new  RegExp(/^[A-Za-z0-9 ():-]+$/),
        regCourseArea : new  RegExp(/^[A-Za-z0-9*-/:;() ]/),
        regCourseName : new RegExp(/^[A-Za-z0-9() :-]*$/),
        regDegreeName : new RegExp(/^[0-9a-zA-Z-/:;() ]+$/),
        regAddress :new RegExp(/^[ A-Za-z0-9#./,-]*$/),
        regCentreName :new  RegExp(/^[a-zA-Z0-9#.,-/ ]*$/) ,
        regCentreCode :new RegExp(/^[a-zA-Z0-9]*$/) ,
        regErpLevelOneName : new RegExp(/^[0-9a-zA-Z- ]*$/),
        regRegistrationNumber : new RegExp(/^[ A-Za-z0-9_]*$/),
        regEmployeeCode : new RegExp(/^[ A-Za-z0-9 ]*$/)
       
 }
 export default ValidationRegPatterns;

